// SPDX-License-Identifier: AGPL-3.0-or-later
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { tokens } from '../src/tokens/source.mjs'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = join(__dirname, '..')
const cssOut = join(root, 'src/styles/tokens.css')
const tsOut = join(root, 'src/tokens/generated.ts')
const checkMode = process.argv.includes('--check')

function validate() {
  const names = new Set()
  for (const token of tokens) {
    if (!token.cssName.startsWith('fx-')) {
      throw new Error(`Token cssName must start with fx-: ${token.cssName}`)
    }
    if (names.has(token.cssName)) {
      throw new Error(`Duplicate token: ${token.cssName}`)
    }
    names.add(token.cssName)

    const hasShared = token.shared !== undefined
    const hasLight = token.light !== undefined
    const hasDark = token.dark !== undefined
    if (hasShared && (hasLight || hasDark)) {
      throw new Error(`Token ${token.cssName} cannot mix shared with light/dark`)
    }
    if (!hasShared && !(hasLight && hasDark)) {
      throw new Error(`Token ${token.cssName} needs shared or both light+dark`)
    }
  }
}

function decl(name, value) {
  return `  --${name}: ${value};`
}

function buildCss() {
  const shared = []
  const light = []
  const dark = []

  for (const token of tokens) {
    if (token.shared !== undefined) {
      shared.push(decl(token.cssName, token.shared))
    } else {
      light.push(decl(token.cssName, token.light))
      dark.push(decl(token.cssName, token.dark))
    }
  }

  return `/* SPDX-License-Identifier: AGPL-3.0-or-later */
/* AUTO-GENERATED by scripts/generate-tokens.mjs — do not edit by hand */

:root,
:root[data-fx-theme='light'],
[data-fx-theme='light'] {
${[...shared, ...light].join('\n')}
}

:root[data-fx-theme='dark'],
[data-fx-theme='dark'] {
${dark.join('\n')}
}

@media (prefers-reduced-motion: reduce) {
  :root,
  [data-fx-theme] {
    --fx-motion-duration-fast: 0.01ms;
    --fx-motion-duration-base: 0.01ms;
    --fx-motion-duration-slow: 0.01ms;
    --fx-motion-duration-slower: 0.01ms;
  }
}
`
}

function setPath(obj, path, value) {
  let cursor = obj
  for (let i = 0; i < path.length - 1; i += 1) {
    const key = path[i]
    if (!(key in cursor) || typeof cursor[key] !== 'object') {
      cursor[key] = {}
    }
    cursor = cursor[key]
  }
  cursor[path[path.length - 1]] = value
}

function serialize(value, indent = 0) {
  const pad = '  '.repeat(indent)
  const padInner = '  '.repeat(indent + 1)
  if (typeof value === 'string') {
    return JSON.stringify(value)
  }
  const keys = Object.keys(value)
  const lines = keys.map((key) => {
    const safeKey = /^[A-Za-z_$][\w$]*$/.test(key) ? key : JSON.stringify(key)
    return `${padInner}${safeKey}: ${serialize(value[key], indent + 1)},`
  })
  return `{\n${lines.join('\n')}\n${pad}}`
}

function buildTs() {
  const tree = {}
  for (const token of tokens) {
    setPath(tree, token.tsPath, `var(--${token.cssName})`)
  }

  return `// SPDX-License-Identifier: AGPL-3.0-or-later
/* AUTO-GENERATED by scripts/generate-tokens.mjs — do not edit by hand */

export const color = ${serialize(tree.color)} as const

export const space = ${serialize(tree.space)} as const

export const size = ${serialize(tree.size)} as const

export const font = ${serialize(tree.font)} as const

export const text = ${serialize(tree.text)} as const

export const radius = ${serialize(tree.radius)} as const

export const shadow = ${serialize(tree.shadow)} as const

export const motion = ${serialize(tree.motion)} as const

export const zIndex = ${serialize(tree.zIndex)} as const

export const component = ${serialize(tree.component)} as const

export const tokens = {
  color,
  space,
  size,
  font,
  text,
  radius,
  shadow,
  motion,
  zIndex,
  component,
} as const

export type ColorToken = keyof typeof color
export type SpaceToken = keyof typeof space
export type RadiusToken = keyof typeof radius
export type ShadowToken = keyof typeof shadow
`
}

validate()
const css = buildCss()
const ts = buildTs()

if (checkMode) {
  const existingCss = readFileSync(cssOut, 'utf8')
  const existingTs = readFileSync(tsOut, 'utf8')
  if (existingCss !== css || existingTs !== ts) {
    console.error('Token outputs are stale. Run npm run tokens:generate')
    process.exit(1)
  }
  console.log('tokens:check ok')
  process.exit(0)
}

mkdirSync(dirname(cssOut), { recursive: true })
mkdirSync(dirname(tsOut), { recursive: true })
writeFileSync(cssOut, css)
writeFileSync(tsOut, ts)
console.log(`wrote ${cssOut}`)
console.log(`wrote ${tsOut}`)
