// SPDX-License-Identifier: AGPL-3.0-or-later
/* AUTO-GENERATED by scripts/generate-tokens.mjs — do not edit by hand */

export const color = {
  bg: "var(--fx-color-bg)",
  bgSubtle: "var(--fx-color-bg-subtle)",
  bgMuted: "var(--fx-color-bg-muted)",
  surface: "var(--fx-color-surface)",
  surfaceRaised: "var(--fx-color-surface-raised)",
  surfaceSunken: "var(--fx-color-surface-sunken)",
  borderSubtle: "var(--fx-color-border-subtle)",
  border: "var(--fx-color-border)",
  borderStrong: "var(--fx-color-border-strong)",
  text: "var(--fx-color-text)",
  textSoft: "var(--fx-color-text-soft)",
  textMuted: "var(--fx-color-text-muted)",
  textDisabled: "var(--fx-color-text-disabled)",
  textInverse: "var(--fx-color-text-inverse)",
  textOnBrand: "var(--fx-color-text-on-brand)",
  brand: "var(--fx-color-brand)",
  brandHover: "var(--fx-color-brand-hover)",
  brandActive: "var(--fx-color-brand-active)",
  brandSoft: "var(--fx-color-brand-soft)",
  brandSoftHover: "var(--fx-color-brand-soft-hover)",
  brandBorder: "var(--fx-color-brand-border)",
  accent: "var(--fx-color-accent)",
  accentHover: "var(--fx-color-accent-hover)",
  accentActive: "var(--fx-color-accent-active)",
  accentSoft: "var(--fx-color-accent-soft)",
  accentBorder: "var(--fx-color-accent-border)",
  success: "var(--fx-color-success)",
  successSoft: "var(--fx-color-success-soft)",
  successBorder: "var(--fx-color-success-border)",
  warning: "var(--fx-color-warning)",
  warningSoft: "var(--fx-color-warning-soft)",
  warningBorder: "var(--fx-color-warning-border)",
  danger: "var(--fx-color-danger)",
  dangerSoft: "var(--fx-color-danger-soft)",
  dangerBorder: "var(--fx-color-danger-border)",
  info: "var(--fx-color-info)",
  infoSoft: "var(--fx-color-info-soft)",
  infoBorder: "var(--fx-color-info-border)",
  focusRing: "var(--fx-color-focus-ring)",
  selectionBg: "var(--fx-color-selection-bg)",
  selectionText: "var(--fx-color-selection-text)",
  overlay: "var(--fx-color-overlay)",
  overlaySoft: "var(--fx-color-overlay-soft)",
} as const

export const space = {
  "0": "var(--fx-space-0)",
  "1": "var(--fx-space-1)",
  "2": "var(--fx-space-2)",
  "3": "var(--fx-space-3)",
  "4": "var(--fx-space-4)",
  "5": "var(--fx-space-5)",
  "6": "var(--fx-space-6)",
  "7": "var(--fx-space-7)",
  "8": "var(--fx-space-8)",
  "10": "var(--fx-space-10)",
  "12": "var(--fx-space-12)",
  "14": "var(--fx-space-14)",
  "16": "var(--fx-space-16)",
  "20": "var(--fx-space-20)",
  "24": "var(--fx-space-24)",
  "32": "var(--fx-space-32)",
  px: "var(--fx-space-px)",
  "0.5": "var(--fx-space-0_5)",
  "1.5": "var(--fx-space-1_5)",
  "2.5": "var(--fx-space-2_5)",
} as const

export const size = {
  control: {
    xs: "var(--fx-size-control-xs)",
    sm: "var(--fx-size-control-sm)",
    md: "var(--fx-size-control-md)",
    lg: "var(--fx-size-control-lg)",
    xl: "var(--fx-size-control-xl)",
  },
  icon: {
    xs: "var(--fx-size-icon-xs)",
    sm: "var(--fx-size-icon-sm)",
    md: "var(--fx-size-icon-md)",
    lg: "var(--fx-size-icon-lg)",
    xl: "var(--fx-size-icon-xl)",
  },
  container: {
    sm: "var(--fx-container-sm)",
    md: "var(--fx-container-md)",
    lg: "var(--fx-container-lg)",
    xl: "var(--fx-container-xl)",
    "2xl": "var(--fx-container-2xl)",
  },
} as const

export const font = {
  sans: "var(--fx-font-sans)",
  heading: "var(--fx-font-heading)",
  mono: "var(--fx-font-mono)",
  weight: {
    regular: "var(--fx-font-weight-regular)",
    medium: "var(--fx-font-weight-medium)",
    semibold: "var(--fx-font-weight-semibold)",
    bold: "var(--fx-font-weight-bold)",
  },
  tracking: {
    tight: "var(--fx-tracking-tight)",
    normal: "var(--fx-tracking-normal)",
    wide: "var(--fx-tracking-wide)",
  },
} as const

export const text = {
  xs: {
    size: "var(--fx-text-xs)",
    leading: "var(--fx-leading-xs)",
  },
  sm: {
    size: "var(--fx-text-sm)",
    leading: "var(--fx-leading-sm)",
  },
  base: {
    size: "var(--fx-text-base)",
    leading: "var(--fx-leading-base)",
  },
  md: {
    size: "var(--fx-text-md)",
    leading: "var(--fx-leading-md)",
  },
  lg: {
    size: "var(--fx-text-lg)",
    leading: "var(--fx-leading-lg)",
  },
  xl: {
    size: "var(--fx-text-xl)",
    leading: "var(--fx-leading-xl)",
  },
  "2xl": {
    size: "var(--fx-text-2xl)",
    leading: "var(--fx-leading-2xl)",
  },
  "3xl": {
    size: "var(--fx-text-3xl)",
    leading: "var(--fx-leading-3xl)",
  },
  "4xl": {
    size: "var(--fx-text-4xl)",
    leading: "var(--fx-leading-4xl)",
  },
  "5xl": {
    size: "var(--fx-text-5xl)",
    leading: "var(--fx-leading-5xl)",
  },
  "6xl": {
    size: "var(--fx-text-6xl)",
    leading: "var(--fx-leading-6xl)",
  },
} as const

export const radius = {
  none: "var(--fx-radius-none)",
  xs: "var(--fx-radius-xs)",
  sm: "var(--fx-radius-sm)",
  md: "var(--fx-radius-md)",
  lg: "var(--fx-radius-lg)",
  xl: "var(--fx-radius-xl)",
  "2xl": "var(--fx-radius-2xl)",
  "3xl": "var(--fx-radius-3xl)",
  full: "var(--fx-radius-full)",
} as const

export const shadow = {
  xs: "var(--fx-shadow-xs)",
  sm: "var(--fx-shadow-sm)",
  md: "var(--fx-shadow-md)",
  lg: "var(--fx-shadow-lg)",
  xl: "var(--fx-shadow-xl)",
  inset: "var(--fx-shadow-inset)",
  ringFocus: "var(--fx-ring-focus)",
} as const

export const motion = {
  duration: {
    instant: "var(--fx-motion-duration-instant)",
    fast: "var(--fx-motion-duration-fast)",
    base: "var(--fx-motion-duration-base)",
    slow: "var(--fx-motion-duration-slow)",
    slower: "var(--fx-motion-duration-slower)",
  },
  ease: {
    linear: "var(--fx-motion-ease-linear)",
    out: "var(--fx-motion-ease-out)",
    in: "var(--fx-motion-ease-in)",
    inOut: "var(--fx-motion-ease-in-out)",
    spring: "var(--fx-motion-ease-spring)",
  },
  fastOut: "var(--fx-motion-fast-out)",
  baseOut: "var(--fx-motion-base-out)",
  slowOut: "var(--fx-motion-slow-out)",
} as const

export const zIndex = {
  hide: "var(--fx-z-hide)",
  base: "var(--fx-z-base)",
  raised: "var(--fx-z-raised)",
  docked: "var(--fx-z-docked)",
  dropdown: "var(--fx-z-dropdown)",
  sticky: "var(--fx-z-sticky)",
  banner: "var(--fx-z-banner)",
  overlay: "var(--fx-z-overlay)",
  modal: "var(--fx-z-modal)",
  popover: "var(--fx-z-popover)",
  toast: "var(--fx-z-toast)",
  tooltip: "var(--fx-z-tooltip)",
  max: "var(--fx-z-max)",
} as const

export const component = {
  dialogWidth: "var(--fx-dialog-width)",
  drawerWidth: "var(--fx-drawer-width)",
  drawerHeight: "var(--fx-drawer-height)",
} as const

export const tokens = {
  color,
  space,
  size,
  font,
  text,
  radius,
  shadow,
  motion,
  zIndex,
  component,
} as const

export type ColorToken = keyof typeof color
export type SpaceToken = keyof typeof space
export type RadiusToken = keyof typeof radius
export type ShadowToken = keyof typeof shadow
